#! /bin/env bash

function package_submodules() {
  find "$1" \
    -type d \
    -exec git config -f .gitmodules -z --fixed-value --get 'submodule.{}.path' '{}' \; \
    -prune
}

function link_file() {
  local src="$1" dst
  dst="$HOME/${src#*/}"
  mkdir -p "$(dirname "$dst")"
  ln -rsfT "$src" "$dst"
  printf '%s -> %s\n' "$dst" "$src"
}

function link_package() {
  local pkg="$1" args f

  args=()
  while IFS= read -r -d '' f; do
    args+=(\! -wholename "$f"'/*')
    link_file "$f"
  done < <(package_submodules "$pkg")

  while IFS= read -r -d '' f; do
    link_file "$f"
  done < <(find "$pkg" ! -type d "${args[@]}" -print0)
}

while [ $# -gt 0 ]; do
  if [ -n "$1" ]; then
    link_package "${1%/}"
  fi
  shift
done
