k9s:
  liveViewAutoRefresh: true
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    enableMouse: true
    headless: false
    logoless: true
    crumbsless: false
    noIcons: false
    reactive: true
    skin: nord
    defaultsToFullScreen: false
  skipLatestRevCheck: true
  logger:
    tail: 1000
    buffer: 10000
    sinceSeconds: -1
    textWrap: true
    disableAutoscroll: false
    showTime: false
  shellPod:
    image: busybox:latest
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
    tty: true
