views:
  v1/namespaces:
    columns:
      - NAME
      - STATUS
      - POLICY:.metadata.labels.pod-security\.kubernetes\.io/enforce
      - LINKERD A:.metadata.annotations.linkerd\.io/inject
      - LINKERD L:.metadata.labels.linkerd\.io/inject
      - AGE
    sortColumn: NAME
