views:
  v1/namespaces:
    columns:
      - NAME
      - STATUS
      - POLICY:.metadata.labels.pod-security\.kubernetes\.io/enforce
      - LINKERD:.metadata.annotations.linkerd\.io/inject
      - AGE
    sortColumn: NAME
