views:
  gateway.networking.k8s.io/v1/listenersets:
    refs:
      - path: /spec/parentRefs/*/name
        kind_path: /spec/parentRefs/*/kind
        group_path: /spec/parentRefs/*/group
        namespace_path: /spec/parentRefs/*/namespace

        group: gateway.networking.k8s.io
        kind: gateways.gateway.networking.k8s.io

        kinds:
          - gateways.gateway.networking.k8s.io

        relation: attaches to
        reverse: cluster
