views:
  v1/namespaces:
    replace: true

    columns:
    - name: NAME
      builtin: NAME
    - name: STATUS
      builtin: STATUS
    - name: POLICY
      path: /metadata/labels/pod-security.kubernetes.io~1enforce
    - name: LINKERD
      path: /metadata/annotations/linkerd.io~1inject
    - name: AGE
      builtin: AGE

    sort: NAME:asc
