---
# yaml-language-server: $schema=https://raw.githubusercontent.com/mostlygeek/llama-swap/refs/heads/main/config-schema.json

captureBuffer: 0

startPort: 11440

macros:
  model: ${MODEL_ID}
  quant: Q4_K_M

  llama-server: /usr/bin/llama-server --port ${PORT} --no-ui --cpu-moe
  llama-server-hf: ${llama-server} -hf ${model}:${quant}

  large-cache: --cache-ram 2048
  small-cache: --cache-ram 512
  no-cache: --cache-ram 0

models:
  Qwopus3.5-9B-Coder:
    name: Qwopus3.5 9B Coder
    cmd: ${llama-server-hf} ${large-cache} --temperature 1.0 --ctx-size 131072
      --batch-size 8192 --ubatch-size 4096 --rope-scaling yarn --rope-scale 4
      --yarn-orig-ctx 32768
    macros:
      model: Jackrong/${MODEL_ID}-GGUF
      quant: Q6_K

  nomic-embed-text-v1.5:
    name: Nomic Embed Text v1.5
    cmd: ${llama-server-hf} ${small-cache} --ctx-size 8192 --batch-size 8192
      --ubatch-size 8192 --rope-scaling yarn --rope-freq-scale 0.75 --embeddings
    macros:
      model: nomic-ai/${MODEL_ID}-GGUF
      quant: Q6_K

  nomic-embed-text-v2-moe:
    name: Nomic Embed Text v2 MoE
    cmd: ${llama-server-hf} ${small-cache} --ctx-size 512 --batch-size 512
      --ubatch-size 512 --embeddings
    macros:
      model: nomic-ai/${MODEL_ID}-GGUF
      quant: Q6_K

  sweep-next-edit-0.5B:
    name: Sweep Next-Edit 0.5B
    cmd: ${llama-server-hf} ${small-cache}
    macros:
      model: sweepai/${MODEL_ID}
      quant: Q8_0

matrix:
  vars:
    qo: Qwopus3.5-9B-Coder
    ne15: nomic-embed-text-v1.5
    ne2m: nomic-embed-text-v2-moe
    sn: sweep-next-edit-0.5B

  evict_costs:
    qo: 50
    ne15: 10
    ne2m: 20
    sn: 10

  sets:
    standard: "(qom | qo) & (ne15 | ne2m) & sn"
